name: apunim
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - tqdm
  - moreutils
  - scikit-learn
  - notebook 
  - ipywidgets
  - statsmodels
  - scipy
  
