name: apunim-experiments
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pandas
  - numpy
  - seaborn
  - tqdm
  - notebook 
  - ipywidgets
  - scikit-learn
  - scipy
  - statsmodels
  - parallel
  
